import type { Product } from "@/types";

// 100+ curated luxury products for seed data
const RAW_PRODUCTS: Product[] = [
  // ── FAUCETS ──
  { id: "faucet-001", name: "Mondrian Single Handle", brand: "Waterworks", category: "faucets", price: 1850, image_url: "/products/faucets/mondrian.jpg", description: "Sculptural single-handle faucet in polished nickel with ceramic disc valve", material: "Solid brass", finish: "Polished Nickel", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["modern", "minimalist"], created_at: "2024-01-01" },
  { id: "faucet-002", name: "Bond Pull-Down", brand: "Brizo", category: "faucets", price: 2340, image_url: "/products/faucets/bond.jpg", description: "Articulating pull-down kitchen faucet with SmartTouch technology", material: "Brass", finish: "Matte Black", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["contemporary", "industrial"], created_at: "2024-01-01" },
  { id: "faucet-003", name: "Tara Classic", brand: "Dornbracht", category: "faucets", price: 3200, image_url: "/products/faucets/tara.jpg", description: "Timeless two-handle faucet with crosshead handles", material: "Brass", finish: "Brushed Durabrass", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["classic", "transitional"], created_at: "2024-01-01" },
  { id: "faucet-004", name: "Vola 111", brand: "Vola", category: "faucets", price: 2890, image_url: "/products/faucets/vola111.jpg", description: "Iconic Danish design wall-mount faucet", material: "Brass", finish: "Brushed Nickel", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["scandinavian", "minimalist"], created_at: "2024-01-01" },
  { id: "faucet-005", name: "Purist Bridge", brand: "Kohler", category: "faucets", price: 1450, image_url: "/products/faucets/purist.jpg", description: "Bridge kitchen faucet with side spray and lever handles", material: "Brass", finish: "Vibrant Stainless", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["transitional", "classic"], created_at: "2024-01-01" },
  { id: "faucet-006", name: "Metris Select", brand: "Hansgrohe", category: "faucets", price: 980, image_url: "/products/faucets/metris.jpg", description: "Push-button kitchen mixer with swivel spout", material: "Brass", finish: "Chrome", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 7, style_tags: ["modern", "functional"], created_at: "2024-01-01" },
  { id: "faucet-007", name: "Newport Brass Jacobean", brand: "Newport Brass", category: "faucets", price: 2100, image_url: "/products/faucets/jacobean.jpg", description: "Traditional widespread lavatory faucet with cross handles", material: "Brass", finish: "Aged Brass", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["traditional", "elegant"], created_at: "2024-01-01" },

  // ── SINKS ──
  { id: "sink-001", name: "Ruvati Verona", brand: "Ruvati", category: "sinks", price: 1200, image_url: "/products/sinks/verona.jpg", description: "36-inch fireclay farmhouse apron-front sink", material: "Fireclay", finish: "White Gloss", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["farmhouse", "classic"], created_at: "2024-01-01" },
  { id: "sink-002", name: "Kohler Stages 45", brand: "Kohler", category: "sinks", price: 2800, image_url: "/products/sinks/stages.jpg", description: "45-inch stainless steel undermount kitchen sink with accessories", material: "Stainless Steel", finish: "Satin", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 9, style_tags: ["modern", "functional"], created_at: "2024-01-01" },
  { id: "sink-003", name: "Native Trails Farmhouse", brand: "Native Trails", category: "sinks", price: 3400, image_url: "/products/sinks/farmhouse-copper.jpg", description: "Hand-hammered copper farmhouse sink with living finish", material: "Copper", finish: "Antique Copper", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 9, style_tags: ["artisan", "rustic"], created_at: "2024-01-01" },
  { id: "sink-004", name: "Duravit Vero", brand: "Duravit", category: "sinks", price: 890, image_url: "/products/sinks/vero.jpg", description: "Rectangular above-counter washbasin with sharp geometric lines", material: "Ceramic", finish: "White Alpin", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["modern", "geometric"], created_at: "2024-01-01" },
  { id: "sink-005", name: "Stone Forest Vessel", brand: "Stone Forest", category: "sinks", price: 4200, image_url: "/products/sinks/stone-vessel.jpg", description: "Hand-carved natural stone vessel sink", material: "Natural Stone", finish: "Honed", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["organic", "luxury"], created_at: "2024-01-01" },
  { id: "sink-006", name: "Blanco Silgranit", brand: "Blanco", category: "sinks", price: 750, image_url: "/products/sinks/silgranit.jpg", description: "Double bowl undermount sink in composite granite", material: "Silgranit", finish: "Anthracite", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 7, style_tags: ["contemporary", "durable"], created_at: "2024-01-01" },

  // ── COUNTERTOPS ──
  { id: "counter-001", name: "Calacatta Borghini", brand: "ABC Stone", category: "countertops", price: 185, image_url: "/products/countertops/calacatta.jpg", description: "Premium Italian marble with dramatic gold and grey veining. Price per sq ft.", material: "Marble", finish: "Polished", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["luxury", "classic"], created_at: "2024-01-01" },
  { id: "counter-002", name: "Taj Mahal Quartzite", brand: "MSI", category: "countertops", price: 145, image_url: "/products/countertops/taj-mahal.jpg", description: "Exotic quartzite with warm golden tones and soft veining. Price per sq ft.", material: "Quartzite", finish: "Polished", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["warm", "elegant"], created_at: "2024-01-01" },
  { id: "counter-003", name: "Soapstone Barroca", brand: "M.Teixeira", category: "countertops", price: 120, image_url: "/products/countertops/soapstone.jpg", description: "Brazilian soapstone with rich charcoal veining. Price per sq ft.", material: "Soapstone", finish: "Honed", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["organic", "matte"], created_at: "2024-01-01" },
  { id: "counter-004", name: "Dekton Entzo", brand: "Cosentino", category: "countertops", price: 95, image_url: "/products/countertops/dekton.jpg", description: "Ultra-compact sintered surface inspired by Calacatta marble. Price per sq ft.", material: "Sintered Stone", finish: "Polished", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["modern", "durable"], created_at: "2024-01-01" },
  { id: "counter-005", name: "Nero Marquina", brand: "ABC Stone", category: "countertops", price: 165, image_url: "/products/countertops/nero-marquina.jpg", description: "Dramatic black marble with crisp white veining. Price per sq ft.", material: "Marble", finish: "Polished", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["dramatic", "bold"], created_at: "2024-01-01" },
  { id: "counter-006", name: "White Oak Butcher Block", brand: "Grothouse", category: "countertops", price: 210, image_url: "/products/countertops/butcher-block.jpg", description: "Premium white oak end-grain butcher block. Price per sq ft.", material: "Wood", finish: "Durata Waterproof", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["warm", "natural"], created_at: "2024-01-01" },
  { id: "counter-007", name: "Terrazzo Palladiana", brand: "Diespeker", category: "countertops", price: 175, image_url: "/products/countertops/terrazzo.jpg", description: "Large chip terrazzo in warm neutral tones. Price per sq ft.", material: "Terrazzo", finish: "Polished", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 7, style_tags: ["artisan", "retro-modern"], created_at: "2024-01-01" },

  // ── CABINETS ──
  { id: "cab-001", name: "Shaker in Alabaster", brand: "Plain & Fancy", category: "cabinets", price: 850, image_url: "/products/cabinets/shaker-white.jpg", description: "Inset shaker door in maple with alabaster finish. Price per linear ft.", material: "Maple", finish: "Alabaster Paint", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["classic", "clean"], created_at: "2024-01-01" },
  { id: "cab-002", name: "Flat Panel Walnut", brand: "Henrybuilt", category: "cabinets", price: 1200, image_url: "/products/cabinets/walnut-flat.jpg", description: "Slab-front walnut cabinet doors with push-to-open mechanism. Price per linear ft.", material: "Walnut", finish: "Natural Oil", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["modern", "warm"], created_at: "2024-01-01" },
  { id: "cab-003", name: "Recessed Panel Sage", brand: "Waterworks", category: "cabinets", price: 980, image_url: "/products/cabinets/sage-recessed.jpg", description: "Recessed panel cabinet in heritage sage green. Price per linear ft.", material: "Poplar", finish: "Sage Paint", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["transitional", "color"], created_at: "2024-01-01" },
  { id: "cab-004", name: "Rift Oak Minimal", brand: "Bulthaup", category: "cabinets", price: 1450, image_url: "/products/cabinets/rift-oak.jpg", description: "Handleless rift-cut white oak with invisible hinges. Price per linear ft.", material: "White Oak", finish: "Matte Lacquer", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 9, style_tags: ["minimalist", "european"], created_at: "2024-01-01" },
  { id: "cab-005", name: "Beaded Inset Navy", brand: "Christopher Peacock", category: "cabinets", price: 1650, image_url: "/products/cabinets/navy-beaded.jpg", description: "Beaded inset cabinetry in Hale Navy with brass hardware. Price per linear ft.", material: "Maple", finish: "Hale Navy Paint", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 9, style_tags: ["traditional", "bold"], created_at: "2024-01-01" },
  { id: "cab-006", name: "Floating Vanity Teak", brand: "RH", category: "cabinets", price: 3200, image_url: "/products/cabinets/floating-teak.jpg", description: "Wall-mounted floating vanity in reclaimed teak", material: "Reclaimed Teak", finish: "Natural", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["modern", "spa"], created_at: "2024-01-01" },

  // ── BACKSPLASH ──
  { id: "back-001", name: "Zellige in Weathered White", brand: "Clé Tile", category: "backsplash", price: 38, image_url: "/products/backsplash/zellige-white.jpg", description: "Handmade Moroccan zellige tiles with natural variation. Price per sq ft.", material: "Zellige", finish: "Glazed", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["artisan", "textured"], created_at: "2024-01-01" },
  { id: "back-002", name: "Calacatta Marble Slab", brand: "ABC Stone", category: "backsplash", price: 165, image_url: "/products/backsplash/calacatta-slab.jpg", description: "Full slab Calacatta marble backsplash. Price per sq ft.", material: "Marble", finish: "Polished", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["luxury", "seamless"], created_at: "2024-01-01" },
  { id: "back-003", name: "Heath Dimensional", brand: "Heath Ceramics", category: "backsplash", price: 52, image_url: "/products/backsplash/heath.jpg", description: "Handcrafted dimensional tiles in varied glazes. Price per sq ft.", material: "Ceramic", finish: "Matte Glaze", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["artisan", "california"], created_at: "2024-01-01" },
  { id: "back-004", name: "Waterjet Arabesque", brand: "Artistic Tile", category: "backsplash", price: 85, image_url: "/products/backsplash/arabesque.jpg", description: "Waterjet-cut marble and brass arabesque mosaic. Price per sq ft.", material: "Marble/Brass", finish: "Polished", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["ornate", "luxury"], created_at: "2024-01-01" },
  { id: "back-005", name: "Matte Black Subway", brand: "Fireclay Tile", category: "backsplash", price: 22, image_url: "/products/backsplash/black-subway.jpg", description: "Handmade 3x6 subway tile in true matte black. Price per sq ft.", material: "Ceramic", finish: "Matte", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["modern", "bold"], created_at: "2024-01-01" },
  { id: "back-006", name: "Terrazzo Micro", brand: "Concrete Collaborative", category: "backsplash", price: 48, image_url: "/products/backsplash/terrazzo-micro.jpg", description: "Micro chip terrazzo tiles in blush tones. Price per sq ft.", material: "Terrazzo", finish: "Honed", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 7, style_tags: ["playful", "retro"], created_at: "2024-01-01" },
  { id: "back-007", name: "Fluted Marble", brand: "Ann Sacks", category: "backsplash", price: 95, image_url: "/products/backsplash/fluted-marble.jpg", description: "Vertically fluted Thassos marble tiles. Price per sq ft.", material: "Marble", finish: "Honed", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["textured", "elegant"], created_at: "2024-01-01" },

  // ── FLOORING ──
  { id: "floor-001", name: "European White Oak Wide Plank", brand: "Dinesen", category: "flooring", price: 32, image_url: "/products/flooring/dinesen-oak.jpg", description: "12-inch wide premium white oak planks, up to 16ft lengths. Price per sq ft.", material: "White Oak", finish: "Natural Oil", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["scandinavian", "luxury"], created_at: "2024-01-01" },
  { id: "floor-002", name: "Encaustic Cement Tile", brand: "Popham Design", category: "flooring", price: 28, image_url: "/products/flooring/encaustic.jpg", description: "Hand-poured cement tiles in geometric patterns. Price per sq ft.", material: "Cement", finish: "Matte", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["artisan", "pattern"], created_at: "2024-01-01" },
  { id: "floor-003", name: "Honed Limestone", brand: "Paris Ceramics", category: "flooring", price: 42, image_url: "/products/flooring/limestone.jpg", description: "French limestone in tumbled antiqued finish. Price per sq ft.", material: "Limestone", finish: "Antiqued", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["classic", "european"], created_at: "2024-01-01" },
  { id: "floor-004", name: "Chevron Parquet Walnut", brand: "Havwoods", category: "flooring", price: 38, image_url: "/products/flooring/chevron-walnut.jpg", description: "Chevron pattern walnut parquet flooring. Price per sq ft.", material: "Walnut", finish: "Matte Lacquer", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["classic", "parisian"], created_at: "2024-01-01" },
  { id: "floor-005", name: "Black Slate Natural", brand: "Stone Source", category: "flooring", price: 18, image_url: "/products/flooring/black-slate.jpg", description: "Natural cleft black slate tiles. Price per sq ft.", material: "Slate", finish: "Natural Cleft", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 7, style_tags: ["organic", "dramatic"], created_at: "2024-01-01" },
  { id: "floor-006", name: "Large Format Porcelain", brand: "Marazzi", category: "flooring", price: 14, image_url: "/products/flooring/large-porcelain.jpg", description: "48x48 porcelain tiles in warm grey concrete look. Price per sq ft.", material: "Porcelain", finish: "Matte", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["modern", "minimal"], created_at: "2024-01-01" },

  // ── LIGHTING ──
  { id: "light-001", name: "Melange Elongated Pendant", brand: "Visual Comfort", category: "lighting", price: 1890, image_url: "/products/lighting/melange.jpg", description: "Alabaster and brass elongated pendant for kitchen islands", material: "Alabaster/Brass", finish: "Antique Brass", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 9, style_tags: ["sculptural", "warm"], created_at: "2024-01-01" },
  { id: "light-002", name: "IC Ceiling Light", brand: "Flos", category: "lighting", price: 750, image_url: "/products/lighting/ic-flos.jpg", description: "Michael Anastassiades blown glass sphere on brass frame", material: "Glass/Brass", finish: "Brushed Brass", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["modern", "iconic"], created_at: "2024-01-01" },
  { id: "light-003", name: "Apparatus Studio Vanity", brand: "Apparatus", category: "lighting", price: 3200, image_url: "/products/lighting/apparatus.jpg", description: "Horsehair and brass vanity light with porcelain diffuser", material: "Brass/Horsehair", finish: "Satin Brass", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["artisan", "statement"], created_at: "2024-01-01" },
  { id: "light-004", name: "Cedar & Moss Alto Sconce", brand: "Cedar & Moss", category: "lighting", price: 320, image_url: "/products/lighting/alto.jpg", description: "Minimalist wall sconce with linen shade", material: "Brass/Linen", finish: "Brushed Brass", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["minimal", "warm"], created_at: "2024-01-01" },
  { id: "light-005", name: "Roll & Hill Modo Chandelier", brand: "Roll & Hill", category: "lighting", price: 8500, image_url: "/products/lighting/modo.jpg", description: "13-globe modular glass and brass chandelier", material: "Glass/Brass", finish: "Brushed Brass", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 9, style_tags: ["modern", "statement"], created_at: "2024-01-01" },
  { id: "light-006", name: "Workstead Lodge Linear", brand: "Workstead", category: "lighting", price: 2400, image_url: "/products/lighting/lodge.jpg", description: "Hand-bent brass linear pendant with patina finish", material: "Brass", finish: "Natural Patina", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["artisan", "industrial"], created_at: "2024-01-01" },
  { id: "light-007", name: "Articolo Fizi Ball", brand: "Articolo", category: "lighting", price: 1650, image_url: "/products/lighting/fizi.jpg", description: "Mouth-blown textured glass pendant", material: "Glass", finish: "Clear Textured", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["organic", "sculptural"], created_at: "2024-01-01" },

  // ── MIRRORS ──
  { id: "mirror-001", name: "Daphne Round Mirror", brand: "Rejuvenation", category: "mirrors", price: 680, image_url: "/products/mirrors/daphne.jpg", description: "36-inch round mirror with thin brass frame", material: "Brass/Glass", finish: "Aged Brass", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["classic", "warm"], created_at: "2024-01-01" },
  { id: "mirror-002", name: "Infinity Frameless", brand: "CB2", category: "mirrors", price: 450, image_url: "/products/mirrors/infinity.jpg", description: "36x24 frameless mirror with polished edge", material: "Glass", finish: "Polished Edge", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["modern", "minimal"], created_at: "2024-01-01" },
  { id: "mirror-003", name: "Arched Floor Mirror", brand: "RH", category: "mirrors", price: 2800, image_url: "/products/mirrors/arched.jpg", description: "7-foot arched metal frame floor mirror", material: "Iron/Glass", finish: "Antique Iron", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["dramatic", "statement"], created_at: "2024-01-01" },
  { id: "mirror-004", name: "Capsule LED Mirror", brand: "West Elm", category: "mirrors", price: 890, image_url: "/products/mirrors/capsule-led.jpg", description: "Backlit capsule mirror with integrated LED and defogger", material: "Aluminum/Glass", finish: "Matte Black", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["modern", "functional"], created_at: "2024-01-01" },
  { id: "mirror-005", name: "Venetian Antiqued", brand: "John Derian", category: "mirrors", price: 3400, image_url: "/products/mirrors/venetian.jpg", description: "Hand-antiqued Venetian glass mirror with foxed finish", material: "Glass", finish: "Antiqued", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["vintage", "romantic"], created_at: "2024-01-01" },

  // ── HARDWARE ──
  { id: "hw-001", name: "Arc Pull 6\"", brand: "Schoolhouse", category: "hardware", price: 48, image_url: "/products/hardware/arc-pull.jpg", description: "Solid brass arc pull in 6-inch center-to-center", material: "Brass", finish: "Aged Brass", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["classic", "warm"], created_at: "2024-01-01" },
  { id: "hw-002", name: "Linear Edge Pull", brand: "Emtek", category: "hardware", price: 32, image_url: "/products/hardware/linear.jpg", description: "Slim profile edge pull for handleless look", material: "Stainless Steel", finish: "Satin Nickel", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 7, style_tags: ["modern", "minimal"], created_at: "2024-01-01" },
  { id: "hw-003", name: "T-Bar Knurled", brand: "Buster + Punch", category: "hardware", price: 65, image_url: "/products/hardware/knurled.jpg", description: "Knurled T-bar pull in solid brass", material: "Brass", finish: "Smoked Bronze", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["industrial", "tactile"], created_at: "2024-01-01" },
  { id: "hw-004", name: "Globe Knob", brand: "Anthropologie", category: "hardware", price: 18, image_url: "/products/hardware/globe.jpg", description: "Hand-cast brass globe knob with patina", material: "Brass", finish: "Natural Brass", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 7, style_tags: ["eclectic", "artisan"], created_at: "2024-01-01" },
  { id: "hw-005", name: "Flat Black Bar Pull", brand: "Top Knobs", category: "hardware", price: 28, image_url: "/products/hardware/flat-bar.jpg", description: "12-inch flat bar pull in matte black", material: "Zinc", finish: "Flat Black", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["modern", "bold"], created_at: "2024-01-01" },
  { id: "hw-006", name: "Leather Wrap Pull", brand: "Turnstyle", category: "hardware", price: 95, image_url: "/products/hardware/leather.jpg", description: "Brass pull wrapped in hand-stitched saddle leather", material: "Brass/Leather", finish: "Polished Brass/Tan", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["warm", "tactile"], created_at: "2024-01-01" },

  // ── APPLIANCES ──
  { id: "appl-001", name: "48\" Dual Fuel Range", brand: "La Cornue", category: "appliances", price: 18500, image_url: "/products/appliances/lacornue.jpg", description: "Château series range in custom color with brass trim", material: "Steel/Brass", finish: "Custom Color", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 9, style_tags: ["luxury", "statement"], created_at: "2024-01-01" },
  { id: "appl-002", name: "Column Refrigerator", brand: "Sub-Zero", category: "appliances", price: 9800, image_url: "/products/appliances/subzero-column.jpg", description: "30-inch integrated column refrigerator with panel-ready design", material: "Stainless Steel", finish: "Panel Ready", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["integrated", "modern"], created_at: "2024-01-01" },
  { id: "appl-003", name: "Pro Range 36\"", brand: "Wolf", category: "appliances", price: 8200, image_url: "/products/appliances/wolf-range.jpg", description: "36-inch gas range with infrared charbroiler and griddle", material: "Stainless Steel", finish: "Stainless", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 9, style_tags: ["professional", "performance"], created_at: "2024-01-01" },
  { id: "appl-004", name: "Panel-Ready Dishwasher", brand: "Miele", category: "appliances", price: 2400, image_url: "/products/appliances/miele-dw.jpg", description: "Fully integrated dishwasher with AutoDos and knock-to-open", material: "Stainless Steel", finish: "Panel Ready", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 7, style_tags: ["integrated", "silent"], created_at: "2024-01-01" },
  { id: "appl-005", name: "Induction Cooktop 36\"", brand: "Gaggenau", category: "appliances", price: 5600, image_url: "/products/appliances/gaggenau-induction.jpg", description: "Full surface induction cooktop with flex zones", material: "Glass Ceramic", finish: "Black", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["modern", "performance"], created_at: "2024-01-01" },
  { id: "appl-006", name: "Ventilation Hood Insert", brand: "Best", category: "appliances", price: 1800, image_url: "/products/appliances/hood-insert.jpg", description: "Built-in ventilation insert for custom hood", material: "Stainless Steel", finish: "Stainless", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 7, style_tags: ["integrated", "functional"], created_at: "2024-01-01" },

  // ── FIXTURES (Bathroom) ──
  { id: "fix-001", name: "Freestanding Soaking Tub", brand: "Victoria + Albert", category: "tub", price: 6800, image_url: "/products/fixtures/freestanding-tub.jpg", description: "Barcelona freestanding tub in volcanic limestone composite", material: "?"/*Volcanic Limestone*/, finish: "Gloss White", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["sculptural", "spa"], created_at: "2024-01-01" },
  { id: "fix-002", name: "Japanese Soaking Tub", brand: "Aquatica", category: "tub", price: 4500, image_url: "/products/fixtures/ofuro.jpg", description: "Deep soaking tub inspired by traditional Japanese ofuro", material: "Solid Surface", finish: "Matte White", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["zen", "minimal"], created_at: "2024-01-01" },
  { id: "fix-003", name: "Rainfall Shower System", brand: "Fantini", category: "shower", price: 4200, image_url: "/products/fixtures/rainfall.jpg", description: "Ceiling-mount 16-inch rainfall shower head with hand shower", material: "Brass", finish: "Brushed Nickel", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["luxury", "spa"], created_at: "2024-01-01" },
  { id: "fix-004", name: "Wall-Mount Toilet", brand: "Toto", category: "toilet", price: 1850, image_url: "/products/fixtures/wall-toilet.jpg", description: "Wall-hung toilet with Washlet bidet seat and concealed tank", material: "Vitreous China", finish: "Cotton White", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["modern", "clean"], created_at: "2024-01-01" },
  { id: "fix-005", name: "Pedestal Tub", brand: "Waterworks", category: "tub", price: 12000, image_url: "/products/fixtures/pedestal-tub.jpg", description: "Cast iron clawfoot tub with polished exterior", material: "Cast Iron", finish: "Polished Nickel Exterior", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["traditional", "statement"], created_at: "2024-01-01" },
  { id: "fix-006", name: "Linear Shower Drain", brand: "Infinity Drain", category: "shower", price: 890, image_url: "/products/fixtures/linear-drain.jpg", description: "36-inch linear shower drain with tile-insert grate", material: "Stainless Steel", finish: "Satin", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 7, style_tags: ["modern", "seamless"], created_at: "2024-01-01" },

  // ── VANITY ──
  { id: "van-001", name: "60\" Double Vanity", brand: "Restoration Hardware", category: "vanity", price: 5400, image_url: "/products/vanity/rh-double.jpg", description: "Weathered oak double vanity with marble top", material: "Oak/Marble", finish: "Weathered", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["transitional", "luxury"], created_at: "2024-01-01" },
  { id: "van-002", name: "Floating Console Vanity", brand: "West Elm", category: "vanity", price: 2200, image_url: "/products/vanity/floating-console.jpg", description: "Wall-mounted console vanity in blackened steel and marble", material: "Steel/Marble", finish: "Blackened", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["modern", "industrial"], created_at: "2024-01-01" },
  { id: "van-003", name: "Vintage Chest Vanity", brand: "Custom", category: "vanity", price: 3800, image_url: "/products/vanity/vintage-chest.jpg", description: "Repurposed vintage chest converted to vanity with stone top", material: "Wood/Stone", finish: "Original Patina", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["eclectic", "one-of-a-kind"], created_at: "2024-01-01" },
  { id: "van-004", name: "Concrete Trough Vanity", brand: "Native Trails", category: "vanity", price: 4600, image_url: "/products/vanity/concrete-trough.jpg", description: "Hand-finished concrete trough vanity with integrated sink", material: "NativeStone Concrete", finish: "Ash", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["organic", "artisan"], created_at: "2024-01-01" },

  // ── Additional products to reach 100+ ──
  { id: "faucet-008", name: "Pot Filler Articulated", brand: "Rohl", category: "faucets", price: 1200, image_url: "/products/faucets/pot-filler.jpg", description: "Wall-mount articulated pot filler with cross handles", material: "Brass", finish: "Polished Nickel", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["functional", "professional"], created_at: "2024-01-01" },
  { id: "sink-007", name: "Integrated Quartz Sink", brand: "Silestone", category: "sinks", price: 1600, image_url: "/products/sinks/integrated.jpg", description: "Integrated quartz sink and countertop in single piece", material: "Quartz", finish: "Matte", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["seamless", "modern"], created_at: "2024-01-01" },
  { id: "counter-008", name: "Concrete Countertop", brand: "Trueform", category: "countertops", price: 135, image_url: "/products/countertops/concrete.jpg", description: "Custom cast concrete countertop with integral sink option. Price per sq ft.", material: "Concrete", finish: "Honed", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["industrial", "artisan"], created_at: "2024-01-01" },
  { id: "cab-007", name: "Glass Front Display", brand: "Plain & Fancy", category: "cabinets", price: 1100, image_url: "/products/cabinets/glass-front.jpg", description: "Mullion glass-front upper cabinet in painted finish. Price per linear ft.", material: "Maple/Glass", finish: "White Paint", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["traditional", "display"], created_at: "2024-01-01" },
  { id: "back-008", name: "Herringbone Marble", brand: "Tilebar", category: "backsplash", price: 42, image_url: "/products/backsplash/herringbone.jpg", description: "1x3 marble herringbone mosaic in Carrara. Price per sq ft.", material: "Marble", finish: "Honed", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["classic", "pattern"], created_at: "2024-01-01" },
  { id: "floor-007", name: "Hex Terracotta", brand: "Tabarka", category: "flooring", price: 24, image_url: "/products/flooring/hex-terracotta.jpg", description: "Handmade hexagonal terracotta tiles. Price per sq ft.", material: "Terracotta", finish: "Natural", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["mediterranean", "warm"], created_at: "2024-01-01" },
  { id: "light-008", name: "Recessed Trim Ring", brand: "Element", category: "lighting", price: 180, image_url: "/products/lighting/recessed.jpg", description: "Trimless recessed downlight with warm dim technology", material: "Aluminum", finish: "White", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 7, style_tags: ["minimal", "architectural"], created_at: "2024-01-01" },
  { id: "hw-007", name: "Stepped Backplate Pull", brand: "Waterworks", category: "hardware", price: 120, image_url: "/products/hardware/stepped.jpg", description: "Stepped backplate with lever pull in unlacquered brass", material: "Brass", finish: "Unlacquered Brass", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["transitional", "classic"], created_at: "2024-01-01" },
  { id: "appl-007", name: "Built-In Coffee System", brand: "Miele", category: "appliances", price: 4200, image_url: "/products/appliances/coffee.jpg", description: "Built-in whole bean coffee system with dual dispensers", material: "Stainless Steel", finish: "Obsidian Black", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["luxury", "integrated"], created_at: "2024-01-01" },
  { id: "fix-007", name: "Thermostatic Shower Panel", brand: "Graff", category: "shower", price: 5800, image_url: "/products/fixtures/thermo-panel.jpg", description: "Full thermostatic shower panel with body jets and rain head", material: "Brass", finish: "Brushed Nickel", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["luxury", "spa"], created_at: "2024-01-01" },
  { id: "mirror-006", name: "Pivoting Vanity Mirror", brand: "Waterworks", category: "mirrors", price: 1200, image_url: "/products/mirrors/pivoting.jpg", description: "Wall-mounted pivoting mirror on brass arm", material: "Brass/Glass", finish: "Unlacquered Brass", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["classic", "functional"], created_at: "2024-01-01" },
  { id: "van-005", name: "Built-In Linen Tower", brand: "Duravit", category: "vanity", price: 2800, image_url: "/products/vanity/linen-tower.jpg", description: "Tall storage cabinet with soft-close doors and interior lighting", material: "MDF", finish: "Graphite Matte", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 7, style_tags: ["modern", "storage"], created_at: "2024-01-01" },
  { id: "fix-008", name: "Bidet Seat", brand: "Toto", category: "toilet", price: 1400, image_url: "/products/fixtures/bidet-seat.jpg", description: "Washlet S7A electronic bidet seat with ewater+", material: "Plastic", finish: "Cotton White", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 7, style_tags: ["modern", "wellness"], created_at: "2024-01-01" },
  { id: "counter-009", name: "Leathered Granite", brand: "Arizona Tile", category: "countertops", price: 88, image_url: "/products/countertops/leathered.jpg", description: "Leathered finish black granite with textured surface. Price per sq ft.", material: "Granite", finish: "Leathered", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["textured", "moody"], created_at: "2024-01-01" },
  { id: "cab-008", name: "Fluted Panel", brand: "SemiHandmade", category: "cabinets", price: 420, image_url: "/products/cabinets/fluted.jpg", description: "Vertically fluted MDF cabinet fronts for IKEA frames. Price per front.", material: "MDF", finish: "Matte White", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["textured", "modern"], created_at: "2024-01-01" },
  { id: "back-009", name: "Glass Slab", brand: "ThinkGlass", category: "backsplash", price: 120, image_url: "/products/backsplash/glass-slab.jpg", description: "Back-painted tempered glass slab backsplash. Price per sq ft.", material: "Glass", finish: "Back-Painted", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["modern", "seamless"], created_at: "2024-01-01" },
  { id: "floor-008", name: "Penny Round Mosaic", brand: "Merola", category: "flooring", price: 16, image_url: "/products/flooring/penny-round.jpg", description: "Porcelain penny round mosaic in matte white. Price per sq ft.", material: "Porcelain", finish: "Matte", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["classic", "bathroom"], created_at: "2024-01-01" },
  { id: "light-009", name: "Picture Light Brass", brand: "Circa Lighting", category: "lighting", price: 480, image_url: "/products/lighting/picture-light.jpg", description: "Slim profile picture light for artwork and mirrors", material: "Brass", finish: "Hand-Rubbed Antique Brass", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["classic", "accent"], created_at: "2024-01-01" },
  { id: "faucet-009", name: "Minimalist Bar Faucet", brand: "Kallista", category: "faucets", price: 1650, image_url: "/products/faucets/bar-faucet.jpg", description: "Cold water bar faucet in minimal cylinder design", material: "Brass", finish: "Matte Black", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["modern", "bar"], created_at: "2024-01-01" },
  { id: "sink-008", name: "Concrete Basin", brand: "Nood Co", category: "sinks", price: 980, image_url: "/products/sinks/concrete-basin.jpg", description: "Hand-cast concrete basin in pill shape", material: "Concrete", finish: "Mid Tone Grey", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["organic", "artisan"], created_at: "2024-01-01" },

  // ── WALLS ──
  { id: "wall-001", name: "Benjamin Moore White Dove", brand: "Benjamin Moore", category: "walls", price: 85, image_url: "/products/walls/white-dove.jpg", description: "Warm white paint with subtle yellow undertone. Price per gallon.", material: "Interior Paint", finish: "Eggshell", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 7, style_tags: ["traditional", "transitional"], created_at: "2024-01-01" },
  { id: "wall-002", name: "Farrow & Ball Hague Blue", brand: "Farrow & Ball", category: "walls", price: 115, image_url: "/products/walls/hague-blue.jpg", description: "Deep dramatic blue with green undertones. Price per gallon.", material: "Interior Paint", finish: "Modern Emulsion", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["traditional", "modern"], created_at: "2024-01-01" },
  { id: "wall-003", name: "Grasscloth Wallpaper Natural", brand: "Phillip Jeffries", category: "walls", price: 280, image_url: "/products/walls/grasscloth.jpg", description: "Natural woven grasscloth wallpaper. Price per roll.", material: "Natural Fibers", finish: "Textured", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["transitional", "farmhouse"], created_at: "2024-01-01" },
  { id: "wall-004", name: "Shiplap Wainscoting Kit", brand: "Metrie", category: "walls", price: 12, image_url: "/products/walls/shiplap.jpg", description: "Pre-primed shiplap wainscoting panels. Price per sq ft.", material: "MDF", finish: "Pre-Primed", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["farmhouse", "transitional"], created_at: "2024-01-01" },
  { id: "wall-005", name: "Lime Wash in Bianco", brand: "Portola Paints", category: "walls", price: 95, image_url: "/products/walls/limewash.jpg", description: "Roman-inspired lime wash with chalky depth. Price per gallon.", material: "Lime Paint", finish: "Matte", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["mediterranean", "modern"], created_at: "2024-01-01" },
  { id: "wall-006", name: "Fluted Wood Accent Panel", brand: "Stikwood", category: "walls", price: 18, image_url: "/products/walls/fluted-panel.jpg", description: "Peel-and-stick fluted wood accent wall panels. Price per sq ft.", material: "Reclaimed Wood", finish: "Natural", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["modern", "industrial"], created_at: "2024-01-01" },
  { id: "wall-007", name: "Venetian Plaster", brand: "Texston", category: "walls", price: 45, image_url: "/products/walls/venetian-plaster.jpg", description: "Polished Venetian plaster wall finish. Price per sq ft installed.", material: "Plaster", finish: "Polished", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["mediterranean", "traditional"], created_at: "2024-01-01" },
  { id: "wall-008", name: "Concrete Effect Paint", brand: "Dulux", category: "walls", price: 65, image_url: "/products/walls/concrete-effect.jpg", description: "Textured concrete-effect wall coating. Price per gallon.", material: "Specialty Paint", finish: "Matte Textured", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 7, style_tags: ["industrial", "modern"], created_at: "2024-01-01" },

  // ── ISLANDS ──
  { id: "island-001", name: "Butcher Block Island", brand: "Boos", category: "islands", price: 3200, image_url: "/products/islands/butcher-block.jpg", description: "48-inch maple butcher block kitchen island with shelf", material: "Maple", finish: "Natural Oil", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 9, style_tags: ["farmhouse", "traditional"], created_at: "2024-01-01" },
  { id: "island-002", name: "Waterfall Quartz Island", brand: "Caesarstone", category: "islands", price: 8500, image_url: "/products/islands/waterfall.jpg", description: "72-inch waterfall edge quartz island in Empira White", material: "Quartz", finish: "Polished", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 9, style_tags: ["modern", "transitional"], created_at: "2024-01-01" },
  { id: "island-003", name: "Portable Kitchen Cart", brand: "Chris & Chris", category: "islands", price: 1400, image_url: "/products/islands/portable-cart.jpg", description: "Stainless steel top portable kitchen island cart", material: "Wood/Stainless", finish: "Natural/Stainless", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 7, style_tags: ["industrial", "farmhouse"], created_at: "2024-01-01" },
  { id: "island-004", name: "Marble Top Island", brand: "Pottery Barn", category: "islands", price: 4800, image_url: "/products/islands/marble-top.jpg", description: "60-inch island with Carrara marble top and brass hardware", material: "Wood/Marble", finish: "White/Polished", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["transitional", "traditional"], created_at: "2024-01-01" },
  { id: "island-005", name: "Reclaimed Wood Island", brand: "West Elm", category: "islands", price: 3600, image_url: "/products/islands/reclaimed.jpg", description: "Reclaimed pine kitchen island with iron base", material: "Reclaimed Pine/Iron", finish: "Natural Distressed", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["industrial", "farmhouse"], created_at: "2024-01-01" },
  { id: "island-006", name: "Custom Lacquer Island", brand: "Henrybuilt", category: "islands", price: 15000, image_url: "/products/islands/lacquer-custom.jpg", description: "Custom-built lacquer island with integrated storage and outlets", material: "MDF", finish: "Custom Lacquer", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 9, style_tags: ["modern", "mediterranean"], created_at: "2024-01-01" },

  // ── STORAGE ──
  { id: "storage-001", name: "Pull-Out Pantry System", brand: "Rev-A-Shelf", category: "storage", price: 680, image_url: "/products/storage/pull-out-pantry.jpg", description: "Tall pull-out pantry with adjustable shelves for 12-inch cabinet", material: "Chrome Wire/Wood", finish: "Chrome/Maple", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["modern", "transitional"], created_at: "2024-01-01" },
  { id: "storage-002", name: "Lazy Susan Corner Unit", brand: "Rev-A-Shelf", category: "storage", price: 420, image_url: "/products/storage/lazy-susan.jpg", description: "32-inch kidney-shaped lazy susan for blind corner cabinets", material: "Polymer", finish: "White", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 7, style_tags: ["traditional", "farmhouse"], created_at: "2024-01-01" },
  { id: "storage-003", name: "Bamboo Drawer Organizer Set", brand: "Marie Kondo", category: "storage", price: 85, image_url: "/products/storage/drawer-organizer.jpg", description: "Modular bamboo drawer organizer set for utensils and cutlery", material: "Bamboo", finish: "Natural", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 7, style_tags: ["farmhouse", "modern"], created_at: "2024-01-01" },
  { id: "storage-004", name: "Floating Shelves Oak", brand: "Shelfology", category: "storage", price: 280, image_url: "/products/storage/floating-shelves.jpg", description: "36-inch heavy-duty floating shelves in white oak", material: "White Oak", finish: "Natural Oil", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["modern", "transitional"], created_at: "2024-01-01" },
  { id: "storage-005", name: "Pot Rack Ceiling Mount", brand: "Enclume", category: "storage", price: 450, image_url: "/products/storage/pot-rack.jpg", description: "Oval ceiling-mount pot rack in hammered steel", material: "Steel", finish: "Hammered Steel", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["industrial", "farmhouse"], created_at: "2024-01-01" },
  { id: "storage-006", name: "Medicine Cabinet Recessed", brand: "Robern", category: "storage", price: 1800, image_url: "/products/storage/medicine-cabinet.jpg", description: "30x40 recessed medicine cabinet with mirrored door and LED", material: "Aluminum/Glass", finish: "Satin Nickel", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["modern", "transitional"], created_at: "2024-01-01" },

  // ── WINDOWS ──
  { id: "window-001", name: "Roman Shade Linen", brand: "The Shade Store", category: "windows", price: 650, image_url: "/products/windows/roman-shade.jpg", description: "Flat roman shade in Belgian linen, custom width up to 48 inches", material: "Belgian Linen", finish: "Ivory", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["traditional", "transitional"], created_at: "2024-01-01" },
  { id: "window-002", name: "Plantation Shutters", brand: "Hunter Douglas", category: "windows", price: 45, image_url: "/products/windows/plantation-shutters.jpg", description: "Composite plantation shutters with 3.5-inch louvers. Price per sq ft.", material: "Composite Wood", finish: "Bright White", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["traditional", "farmhouse"], created_at: "2024-01-01" },
  { id: "window-003", name: "Roller Shade Blackout", brand: "Lutron", category: "windows", price: 480, image_url: "/products/windows/roller-shade.jpg", description: "Motorized roller shade with blackout fabric and quiet motor", material: "Polyester", finish: "White", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 7, style_tags: ["modern", "industrial"], created_at: "2024-01-01" },
  { id: "window-004", name: "Woven Wood Shade", brand: "Smith & Noble", category: "windows", price: 380, image_url: "/products/windows/woven-wood.jpg", description: "Natural woven wood shade in warm bamboo weave", material: "Bamboo/Jute", finish: "Natural", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["farmhouse", "mediterranean"], created_at: "2024-01-01" },
  { id: "window-005", name: "Café Curtain Rod Set", brand: "Rejuvenation", category: "windows", price: 120, image_url: "/products/windows/cafe-curtain.jpg", description: "Brass café curtain rod with ring clips, 28-48 inch adjustable", material: "Brass", finish: "Aged Brass", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 7, style_tags: ["traditional", "farmhouse"], created_at: "2024-01-01" },
  { id: "window-006", name: "Frosted Privacy Film", brand: "Artscape", category: "windows", price: 35, image_url: "/products/windows/privacy-film.jpg", description: "Etched glass privacy window film, repositionable", material: "Vinyl", finish: "Frosted", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 6, style_tags: ["modern", "industrial"], created_at: "2024-01-01" },

  // ── DOORS ──
  { id: "door-001", name: "Shaker Interior Door", brand: "Metrie", category: "doors", price: 380, image_url: "/products/doors/shaker.jpg", description: "5-panel shaker style solid core interior door", material: "MDF/Pine", finish: "Primed White", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["traditional", "transitional"], created_at: "2024-01-01" },
  { id: "door-002", name: "Sliding Barn Door", brand: "Rustica", category: "doors", price: 1200, image_url: "/products/doors/barn-door.jpg", description: "Reclaimed wood sliding barn door with matte black hardware", material: "Reclaimed Wood", finish: "Natural Distressed", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["farmhouse", "industrial"], created_at: "2024-01-01" },
  { id: "door-003", name: "French Door Pair", brand: "Jeld-Wen", category: "doors", price: 1800, image_url: "/products/doors/french-door.jpg", description: "Interior French door pair with clear tempered glass", material: "Wood/Glass", finish: "Primed", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["traditional", "mediterranean"], created_at: "2024-01-01" },
  { id: "door-004", name: "Pocket Door Frame Kit", brand: "Johnson Hardware", category: "doors", price: 320, image_url: "/products/doors/pocket-door.jpg", description: "Soft-close pocket door frame kit for 36-inch door", material: "Steel", finish: "Zinc Plated", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 7, style_tags: ["modern", "transitional"], created_at: "2024-01-01" },
  { id: "door-005", name: "Glass Pivot Door", brand: "Portapivot", category: "doors", price: 4500, image_url: "/products/doors/pivot-glass.jpg", description: "Frameless glass pivot door with concealed floor spring", material: "Tempered Glass", finish: "Clear", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["modern", "industrial"], created_at: "2024-01-01" },
  { id: "door-006", name: "Arched Interior Door", brand: "Simpson Door", category: "doors", price: 2200, image_url: "/products/doors/arched.jpg", description: "Custom arched top interior door in solid wood", material: "Solid Wood", finish: "Stain Grade", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["mediterranean", "traditional"], created_at: "2024-01-01" },

  // ── EXPANDED SHOWER ──
  { id: "shower-001", name: "Frameless Glass Enclosure", brand: "DreamLine", category: "shower", price: 2800, image_url: "/products/shower/frameless-glass.jpg", description: "48-inch frameless hinged shower door in 3/8-inch clear glass", material: "Tempered Glass", finish: "Brushed Nickel", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["modern", "transitional"], created_at: "2024-01-01" },
  { id: "shower-002", name: "Rain Shower Head 12\"", brand: "Kohler", category: "shower", price: 680, image_url: "/products/shower/rain-head.jpg", description: "12-inch ceiling-mount rain shower head with 2.5 GPM flow", material: "Brass", finish: "Polished Chrome", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["modern", "transitional"], created_at: "2024-01-01" },
  { id: "shower-003", name: "Teak Shower Bench", brand: "Aqua Teak", category: "shower", price: 350, image_url: "/products/shower/teak-bench.jpg", description: "24-inch teak wood corner shower bench with shelf", material: "Teak", finish: "Natural Oil", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 7, style_tags: ["farmhouse", "mediterranean"], created_at: "2024-01-01" },
  { id: "shower-004", name: "Shower Niche Stainless", brand: "Tile Redi", category: "shower", price: 180, image_url: "/products/shower/niche.jpg", description: "16x28 prefabricated recessed shower niche", material: "Stainless Steel", finish: "Brushed", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 7, style_tags: ["modern", "industrial"], created_at: "2024-01-01" },

  // ── EXPANDED APPLIANCES ──
  { id: "appl-008", name: "Panel-Ready Dishwasher", brand: "Bosch", category: "appliances", price: 1800, image_url: "/products/appliances/bosch-dw.jpg", description: "800 series panel-ready dishwasher with CrystalDry technology", material: "Stainless Steel", finish: "Panel Ready", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 7, style_tags: ["modern", "transitional"], created_at: "2024-01-01" },
  { id: "appl-009", name: "Built-In Microwave Drawer", brand: "Sharp", category: "appliances", price: 1400, image_url: "/products/appliances/microwave-drawer.jpg", description: "24-inch built-in microwave drawer with sensor cooking", material: "Stainless Steel", finish: "Stainless", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 7, style_tags: ["modern", "industrial"], created_at: "2024-01-01" },
  { id: "appl-010", name: "Wall Mount Vent Hood", brand: "Zephyr", category: "appliances", price: 2200, image_url: "/products/appliances/vent-hood.jpg", description: "36-inch wall mount chimney hood with LED lighting", material: "Stainless Steel", finish: "Stainless", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["modern", "industrial"], created_at: "2024-01-01" },
  { id: "appl-011", name: "Under-Counter Wine Cooler", brand: "Sub-Zero", category: "appliances", price: 3800, image_url: "/products/appliances/wine-cooler.jpg", description: "24-inch under-counter wine storage with 46-bottle capacity", material: "Stainless Steel/Glass", finish: "Panel Ready", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["modern", "traditional"], created_at: "2024-01-01" },

  // ── EXPANDED LIGHTING ──
  { id: "light-010", name: "Under-Cabinet LED Strip", brand: "WAC Lighting", category: "lighting", price: 120, image_url: "/products/lighting/under-cabinet-led.jpg", description: "24-inch dimmable under-cabinet LED light bar, 3000K", material: "Aluminum", finish: "White", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 7, style_tags: ["modern", "industrial"], created_at: "2024-01-01" },
  { id: "light-011", name: "Pendant Cluster 3-Light", brand: "West Elm", category: "lighting", price: 450, image_url: "/products/lighting/pendant-cluster.jpg", description: "3-light cluster pendant with smoked glass globes", material: "Brass/Glass", finish: "Antique Brass", room_type: ["kitchen"], is_insertion_ready: true, pose_rating: 8, style_tags: ["modern", "industrial"], created_at: "2024-01-01" },
  { id: "light-012", name: "Recessed LED Wafer 6\"", brand: "Halo", category: "lighting", price: 45, image_url: "/products/lighting/recessed-wafer.jpg", description: "6-inch ultra-thin LED recessed downlight, 2700K warm white", material: "Aluminum", finish: "White", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 6, style_tags: ["modern", "transitional"], created_at: "2024-01-01" },
  { id: "light-013", name: "Crystal Chandelier Mini", brand: "Visual Comfort", category: "lighting", price: 2800, image_url: "/products/lighting/chandelier-mini.jpg", description: "Small crystal chandelier with hand-polished facets", material: "Crystal/Brass", finish: "Polished Nickel", room_type: ["kitchen", "bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["traditional", "mediterranean"], created_at: "2024-01-01" },

  // ── EXPANDED TOILETS ──
  { id: "toilet-001", name: "One-Piece Elongated", brand: "Kohler", category: "toilet", price: 950, image_url: "/products/toilet/one-piece.jpg", description: "Sleek one-piece elongated toilet with soft-close seat", material: "Vitreous China", finish: "White", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 8, style_tags: ["modern", "transitional"], created_at: "2024-01-01" },
  { id: "toilet-002", name: "Smart Bidet Toilet", brand: "Toto", category: "toilet", price: 4800, image_url: "/products/toilet/smart-toilet.jpg", description: "Neorest NX2 integrated bidet toilet with auto open/close", material: "Vitreous China", finish: "Cotton White", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 9, style_tags: ["modern", "industrial"], created_at: "2024-01-01" },
  { id: "toilet-003", name: "Comfort Height Two-Piece", brand: "American Standard", category: "toilet", price: 480, image_url: "/products/toilet/comfort-height.jpg", description: "ADA-compliant comfort height two-piece toilet", material: "Vitreous China", finish: "White", room_type: ["bathroom"], is_insertion_ready: true, pose_rating: 7, style_tags: ["traditional", "farmhouse"], created_at: "2024-01-01" },
];

// Use the original image_url from RAW_PRODUCTS (descriptive paths).
// The /images/N.png mapping is no longer used — those files don't exist
// and the mapping broke the name-to-image association.
export const SEED_PRODUCTS: Product[] = RAW_PRODUCTS;

export function getProductById(id: string): Product | undefined {
  return SEED_PRODUCTS.find((p) => p.id === id);
}
